### ISSUE TITLE
Don't throw Arduino error until serial port is set

### ISSUE THREAD

**Issue by SparkyXI** [uCtrlDev/Lync-presence-bridge#3]
Hey - forgive me if I come across as "less-than-skilled," but how exactly does one implement this program / code?

**Comment by thomasjsn** [comment]
Hey. It's the source files for Visual Studio, so you would open them there.

I have created a pre-release with binary files, these you can just run like any other application. https://github.com/uCtrlDev/Lync-presence-bridge/releases/tag/v0.1-beta

Let me know if it doesn't run :)

**Comment by SparkyXI** [comment]
Awesome - thanks for the beta. It throws an error on startup "Could not open and init serial port," which  I'm sure is referring to Arduino (I'm using the Blink, if you couldn't guess). After that, it does respond to Lync status changes.

What I'd love to see happen at some point is this actually built into a script that can be run from the Blink(1) Control program - I mentioned this to renenulsch at some point, but he never responded to the query.

**Comment by thomasjsn** [comment]
Yeah, that is referring to the Arduino. I will make a change so that it doesn't throw any errors until a port for the Arduino has been selected.

This app is meant to be a bridge for the blink(1), [Luxafor](http://luxafor.com/) and Arduino. So this can not be run as a script in the blink(1) control program.
